[book]
title = "LFE Quick Start with rebar3_lfe"
author = "Duncan McGreggor"
description = "An Introduction to LFE: Going Ludicrous Speed"
language = "en"

[build]
build-dir = "book"

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "lfe-pdp"
preferred-dark-theme = "lfe-pdp"
google-analytics = "UA-38274766-4"
git-repository-url = "https://github.com/lfe/rebar3-quick-start"
[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
